pretrained_path: /home/jayll/VoxCPM/pretrained/VoxCPM-0.5B
train_manifest: /mnt/d/tts_dataset/metadata.jsonl
val_manifest: null
sample_rate: 16000
batch_size: 16
grad_accum_steps: 1  # Gradient accumulation steps, >1 can increase effective batch size without increasing memory
num_workers: 2
num_iters: 2000
log_interval: 10
valid_interval: 1000
save_interval: 1000
learning_rate: 0.00001 
weight_decay: 0.01
warmup_steps: 100
max_steps: 2000
max_batch_tokens: 8192  # Example: single batch can have at most 16k tokens, with batch_size=4, each sample can have at most 4096 tokens
save_path: /home/jayll/VoxCPM/checkpoints/0.5B
tensorboard: /home/jayll/VoxCPM/logs/0.5B
lambdas:
  loss/diff: 1.0
  loss/stop: 1.0
